//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATO
    {
        public int IdDato { get; set; }
        public string Nombre { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
    }
}
