//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProducto
    {
        public int IdDetalleProducto { get; set; }
        public int IdProducto { get; set; }
        public string PesoMaximo { get; set; }
        public string TiempoApertura { get; set; }
        public string Motor { get; set; }
        public string Reduccion { get; set; }
        public string Central { get; set; }
        public string Complemento { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
