//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especificacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Especificacione()
        {
            this.ProductoEspecificaciones = new HashSet<ProductoEspecificacione>();
        }
    
        public int IdEspecificacion { get; set; }
        public string Texto { get; set; }
        public int Orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoEspecificacione> ProductoEspecificaciones { get; set; }
    }
}
