//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoEspecificacione
    {
        public int IdProducto { get; set; }
        public int IdEspecificacion { get; set; }
        public string Valor { get; set; }
    
        public virtual Especificacione Especificacione { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
